// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2eLP4xulBorU4F5fGX8ruaiTxfkqI_Qw',
    appId: '1:345054622516:web:0ee47fb135c88e53e62b61',
    messagingSenderId: '345054622516',
    projectId: 'crypto-app-fadec',
    authDomain: 'crypto-app-fadec.firebaseapp.com',
    storageBucket: 'crypto-app-fadec.firebasestorage.app',
    measurementId: 'G-XP8W3VMLKR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr42vwJpPHuYeQu09J0-YiazWaRFWcSNE',
    appId: '1:345054622516:android:051072b2821d092be62b61',
    messagingSenderId: '345054622516',
    projectId: 'crypto-app-fadec',
    storageBucket: 'crypto-app-fadec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGbrRPBzfCOKIj-b5gXIY8AqN6glqrkVw',
    appId: '1:345054622516:ios:c849b3a7a1ae606be62b61',
    messagingSenderId: '345054622516',
    projectId: 'crypto-app-fadec',
    storageBucket: 'crypto-app-fadec.firebasestorage.app',
    iosBundleId: 'com.example.crptApp0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGbrRPBzfCOKIj-b5gXIY8AqN6glqrkVw',
    appId: '1:345054622516:ios:c849b3a7a1ae606be62b61',
    messagingSenderId: '345054622516',
    projectId: 'crypto-app-fadec',
    storageBucket: 'crypto-app-fadec.firebasestorage.app',
    iosBundleId: 'com.example.crptApp0',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2eLP4xulBorU4F5fGX8ruaiTxfkqI_Qw',
    appId: '1:345054622516:web:dc398e7c6774c398e62b61',
    messagingSenderId: '345054622516',
    projectId: 'crypto-app-fadec',
    authDomain: 'crypto-app-fadec.firebaseapp.com',
    storageBucket: 'crypto-app-fadec.firebasestorage.app',
    measurementId: 'G-8DSK1P7EL5',
  );

}